server:
  port: 8888

spring:
  application:
    name: sienna
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sienna011022/config-test-server.git
  config:
    import: optional:configserver:http://localhost:8888
    use-legacy-processing: true
